### ISSUE TITLE
"Applications" button isn't aligned to the other panel elements

### ISSUE THREAD

**Issue by sancio6** [rastersoft/slingshot_gnome#1]
Hi! I'd like to ask you why "Applications" button isn't aligned to the other panel elements. It is a gnome-shell thing or it can be fixed? Anyway, keep on the good work! :)

**Comment by rastersoft** [comment]
Yes, I know. Unfortunately I've been unable to fix it :(

**Comment by sancio6** [comment]
:( It would be nice to have it fixed! Anyway, great extension! Apart from that detail, it works pretty good!

**Comment by rastersoft** [comment]
Fixed by an user.
